/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sonnesen.gerenciadorescolar.view;

import com.sonnesen.gerenciadorescolar.util.JPAUtil;

/**
 *
 * @author visitante
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        usuarioManutButton = new javax.swing.JButton();
        alunoManutButton = new javax.swing.JButton();
        usuarioConsultButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador Escolar");
        setExtendedState(6);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        usuarioManutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/user_48_hot.png"))); // NOI18N
        usuarioManutButton.setToolTipText("Manutenção de Usuários");
        usuarioManutButton.setFocusable(false);
        usuarioManutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioManutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuarioManutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioManutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(usuarioManutButton);

        alunoManutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/clients_48_hot.png"))); // NOI18N
        alunoManutButton.setToolTipText("Manutenção de Alunos");
        alunoManutButton.setFocusable(false);
        alunoManutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunoManutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alunoManutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoManutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alunoManutButton);

        usuarioConsultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/clients_search_48_hot.png"))); // NOI18N
        usuarioConsultButton.setToolTipText("Consulta de Alunos");
        usuarioConsultButton.setFocusable(false);
        usuarioConsultButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioConsultButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usuarioConsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioConsultButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(usuarioConsultButton);
        jToolBar1.add(filler1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/door_level_48_hot.png"))); // NOI18N
        jButton3.setToolTipText("Sair");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jMenu1.setText("Manutenção");

        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Aluno");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Curso");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        jMenuItem2.setText("Usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Aluno");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Curso");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 356, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioManutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioManutButtonActionPerformed
        ManutencaoUsuarioView.main(null);
    }//GEN-LAST:event_usuarioManutButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ManutencaoUsuarioView.main(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JPAUtil.closeEntityManagerFactory();
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ManutencaoAlunoView.main(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void alunoManutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoManutButtonActionPerformed
        // TODO add your handling code here:
        ManutencaoAlunoView.main(null);
    }//GEN-LAST:event_alunoManutButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ConsultaAlunoView.main(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void usuarioConsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioConsultButtonActionPerformed
        ConsultaAlunoView.main(null);
    }//GEN-LAST:event_usuarioConsultButtonActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ManutencaoCursoView.main(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alunoManutButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton usuarioConsultButton;
    private javax.swing.JButton usuarioManutButton;
    // End of variables declaration//GEN-END:variables
}
